# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile C with /var/tmp/sparkling-matrix-recovery/toolchains/gnat/gnat-x86_64-linux-16.1.0-1/bin/gcc
# compile CXX with /var/tmp/sparkling-matrix-recovery/toolchains/gnat/gnat-x86_64-linux-16.1.0-1/bin/g++
C_DEFINES = -DCCD_STATIC_DEFINE -DMC_IMPLEM_ENABLE -DMINIZ_STATIC_DEFINE -DMUJOCO_DLL_EXPORTS -DTINYOBJLOADER_IMPLEMENTATION -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DmjUSEPLATFORMSIMD -Dmujoco_EXPORTS

C_INCLUDES = -I/var/tmp/sparkling-movement-c/build/_deps/marchingcubecpp-src -I/var/tmp/sparkling-movement-c/source/include -I/var/tmp/sparkling-movement-c/source/src -I/var/tmp/sparkling-movement-c/build/_deps/tinyobjloader-src -I/var/tmp/sparkling-movement-c/build/_deps/miniz-src -I/var/tmp/sparkling-movement-c/build/_deps/miniz-build -I/var/tmp/sparkling-movement-c/build/_deps/ccd-src/src -I/var/tmp/sparkling-movement-c/build/_deps/ccd-build/src -I/var/tmp/sparkling-movement-c/build/_deps/lodepng-src -I/var/tmp/sparkling-movement-c/build/_deps/qhull-src/src -I/var/tmp/sparkling-movement-c/build/_deps/qhull-src/src/libqhull_r -I/var/tmp/sparkling-movement-c/build/_deps/tinyxml2-src

C_FLAGS = -O3 -march=native -ffp-contract=off -ffinite-math-only -fno-trapping-math -fno-math-errno -std=c11 -flto=auto -fno-fat-lto-objects -fPIC -fvisibility=hidden -fdata-sections -ffunction-sections -mavx -Werror -Wall -Wpedantic -Wimplicit-fallthrough -Wunused -Wvla -Wno-int-in-bool-context -Wno-sign-compare -Wno-unknown-pragmas -Wimplicit-fallthrough=5 -Wno-maybe-uninitialized

CXX_DEFINES = -DCCD_STATIC_DEFINE -DMC_IMPLEM_ENABLE -DMINIZ_STATIC_DEFINE -DMUJOCO_DLL_EXPORTS -DTINYOBJLOADER_IMPLEMENTATION -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DmjUSEPLATFORMSIMD -Dmujoco_EXPORTS

CXX_INCLUDES = -I/var/tmp/sparkling-movement-c/build/_deps/marchingcubecpp-src -I/var/tmp/sparkling-movement-c/source/include -I/var/tmp/sparkling-movement-c/source/src -I/var/tmp/sparkling-movement-c/build/_deps/tinyobjloader-src -I/var/tmp/sparkling-movement-c/build/_deps/miniz-src -I/var/tmp/sparkling-movement-c/build/_deps/miniz-build -I/var/tmp/sparkling-movement-c/build/_deps/ccd-src/src -I/var/tmp/sparkling-movement-c/build/_deps/ccd-build/src -I/var/tmp/sparkling-movement-c/build/_deps/lodepng-src -I/var/tmp/sparkling-movement-c/build/_deps/qhull-src/src -I/var/tmp/sparkling-movement-c/build/_deps/qhull-src/src/libqhull_r -I/var/tmp/sparkling-movement-c/build/_deps/tinyxml2-src

CXX_FLAGS = -O3 -march=native -ffp-contract=off -ffinite-math-only -fno-trapping-math -fno-math-errno -std=c++20 -flto=auto -fno-fat-lto-objects -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -mavx -Werror -Wall -Wpedantic -Wimplicit-fallthrough -Wunused -Wvla -Wno-int-in-bool-context -Wno-sign-compare -Wno-unknown-pragmas -Wimplicit-fallthrough=5 -Wno-maybe-uninitialized

